# Configuracion remota opcional para api-gateway, servida por el Config
# Server en modo nativo. El Gateway, igual que los demas servicios, trae
# esta misma configuracion embebida en su propio application.yml para
# poder arrancar de forma autonoma (modo hibrido Docker/local).
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

spring:
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - AddResponseHeader=X-Gateway-Source, RestaurantEnzo-Gateway
          routes:
            - id: autenticacion-service
              uri: lb://autenticacion-service
              predicates:
                - Path=/api/v1/usuarios/**
            - id: clientes-service
              uri: lb://clientes-service
              predicates:
                - Path=/api/v1/clientes/**
            - id: productos-service
              uri: lb://productos-service
              predicates:
                - Path=/api/v1/productos/**
            - id: pedidos-service
              uri: lb://pedidos-service
              predicates:
                - Path=/api/v1/pedidos/**
            - id: reservas-service
              uri: lb://reservas-service
              predicates:
                - Path=/api/v1/reservas/**
            - id: empleados-service
              uri: lb://empleados-service
              predicates:
                - Path=/api/v1/empleados/**
            - id: locales-service
              uri: lb://locales-service
              predicates:
                - Path=/api/v1/locales/**
            - id: envios-service
              uri: lb://envios-service
              predicates:
                - Path=/api/v1/envios/**
            - id: inventario-service
              uri: lb://inventario-service
              predicates:
                - Path=/api/v1/inventario/**
            - id: pagos-service
              uri: lb://pagos-service
              predicates:
                - Path=/api/v1/pagos/**
